### PR TITLE
[Do not merge]replaced ZOWE_EXPLORER_HOST with ZOWE_IP_ADDRESS

### PR DESCRIPTION
**Pull request by NakulManchanda**
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>

### CODE REVIEW

**Comment by NakulManchanda** [comment]
In ZVM/ZD&T systems, values in instance.env looks like this:

```
ZOWE_EXPLORER_HOST=S0W1.DAL-EBIS.IHOST.COM
ZOWE_IP_ADDRESS=192.86.32.67
```
where ZOWE_EXPLORER_HOST is not public dns name or ip
whereas ZOWE_IP_ADDRESS is public ip

So, when embedding the JES Explorer inside Zowe Desktop
IFRAME URL - `https://192.86.32.67:7554/ui/v1/explorer-jes` - makes more sense
over  existing `https://S0W1.DAL-EBIS.IHOST.COM:7554/ui/v1/explorer-jes`

image


Same goes for CSP setting, as zowe desktop is accessed with url:
`https://192.86.32.67:8544/` - CSP need to use public IP as well to avoid CSP error

image

i believe above two changes will provide default settings which are better suited to all scenarios.

**Comment by NakulManchanda** [comment]
@stevenhorsman @1000TurquoisePogs 
Would be great if we can get more perspective on this from other squads and members.
If this change is appropriate, we need to do the same for 
USS
MVS
API-CATALOG
and other default apps which produce  `zluxiframe index.html`

**Comment by 1000TurquoisePogs** [comment]
It should match the URL that people use to get to the APIML. A hostname is better than an IP when possible, so it may be better to have a variable like ZOWE_NETWORK_ADDRESS which is a hostname or ip.

You could actually make CSP variable. When a request comes in, if the header "hostname" is set, you can see if hostname matches one of your IP or hostnames known to the system. If it does, you could adjust the CSP header to be identical so that it does not fail. However, if it does not match, you can generically return the CSP the way you do now, so that if the hostname really was not from your system then it will not harm security.

**Comment by NakulManchanda** [comment]
> It should match the URL that people use to get to the APIML. A hostname is better than an IP when possible, so it may be better to have a variable like ZOWE_NETWORK_ADDRESS which is a hostname or ip.

yes, its a better way to put it ` URL that people use to get to the APIML`, **but need a way to figure whats the APIML url, any suggestions @stevenhorsman,?

Based on how we find API ML URL if solution is general enough we can introduce utility,
We can call the result of that utility ZOWE_NETWORK_ADDRESS in component scripts locally.

**Comment by stevenhorsman** [comment]
@NakulManchanda - I don't understand the question. the gateway is started on the same host/ip_addess at all the other services?

**Comment by NakulManchanda** [comment]
-> @NakulManchanda - I don't understand the question. the gateway is started on the same host/ip_addess at all the other services?

**if hostname is preferable, is there a way to determine hostname is client accessible or not?**

Just restating problem again,
Basically trying to figure out ZOWE_EXPLORER_HOST accessible from client side or not.

On ZD&T system
ZOWE_EXPLORER_HOST=S0W1.DAL-EBIS.IHOST.COM **#Not Public hostname**
ZOWE_IP_ADDRESS=192.86.32.67 #Public IP Address
Here api ml was accessed through ip, **https://ZOWE_IP_ADDRESS:7554**

But other systems:
ZOWE_EXPLORER_HOST=tvt500x.svl.ibm.com #public
ZOWE_IP_ADDRESS=9.x.x.x #public
Here api ml can be accessed via both from client  
 _https://ZOWE_EXPLORER_HOST:7554_
 _https://ZOWE_IP_ADDRESS:7554_

**But as we generate static zluxiframe index.html using configure.sh, while executing run-zowe.sh,** 
**Suggestion 1:** Always use IP - like in PR here
**Suggestion 2??:** if hostname pattern matches S0W1*, only then use IP - **not sure this true**
**Suggestion 3??** -   is there any other way to find hostname is public or not during run-zowe ?
**Suggestion 4??** - can we make these zluxiframe url  - as they are in runtime folder, more dynamic?

Here how it looks like right now:
**zowe-instance-dir/workspace/explorer-jes/web #>cat index.html**
What PR Does is - replace ZOWE_EXPLORER_HOST => ZOWE_IP_ADDRESS always
```
<!DOCTYPE html>
<html>
    <body>
        <iframe
            id="zluxIframe"
            src="https://ZOWE_EXPLORER_HOST:7554/ui/v1/explorer-jes";
            style="position:fixed; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;">
            Your browser doesn't support iframes
        </iframe>
    </body>
</html>
```

**Comment by stevenhorsman** [comment]
I think for suggestion 3 (trying to avoid suggestion 2) @John-A-Davies did something to try doing a dig command to test if the hostname resolved to an external IP, so we might be able to use that to tell?
As I said yesterday, I'd prefer to not just use the ip in all the scripts, but instead try setting ZOWE_EXPLORER_HOST=${ZOWE_IP_ADDRESS} in instance.env if the host we get bad and seeing if that fixes the problem.

**Comment by NakulManchanda** [comment]
ok, sure 
@John-A-Davies any suggestions to find hostname is public or not when executing run-zowe.sh is appreciated. 
Eg:  specific to ZD&T systems- hostname **S0W1.DAL-EBIS.IHOST.COM**,   is not public hostname.

**Comment by Joe-Winchester** [comment]
This has identified a problem with how the instance.env file populates its ZOWE_HOST_NAME and ZOWE_IP_ADDRESS variables.  
Defect https://github.com/zowe/zowe-install-packaging/issues/1279 will address this earlier in the configure pipeline.

**Comment by NakulManchanda** [comment]
Issue being addressed by @John-A-Davies as part of zowe install with this PR
https://github.com/zowe/zowe-install-packaging/pull/1323

Issue test by @NayerNajafi

thanks!

**Comment by jackjia-ibm** [comment]
@NakulManchanda @stevenhorsman @Joe-Winchester I think this fix is wrong. We should prefer domain name other than hardcode/always use IP address in URL. If the user decide to configure ZOWE_EXPLORER_HOST to be ip address, that's his choice, our code should be ok. But if the user prefer to use domain, this fix will cause the JES explorer always pop a certificate failure, even though the user import and trusted the certificate for his domain. For example, the user import and trust `*.svl.ibm.com` certificate and visit `https://tvt5003.svl.ibm.com:7544`, he will see a green lock which mean the certificate is verified. But when he navigates to JES explorer, he will be popped up certificate failure. This is not a big issue for development with self-signed certificates, but for production which uses external certificates, this will become an issue.

**Comment by jackjia-ibm** [comment]
Maybe an example to better explain why. Clicking on the github.com certificate, and looking for the SAN (Subject Alternative Name) section, you will see it has 2 DNS Name configured: github.com and www.github.com. It doesn't have any IP address defined in the certificate. If you connect github.com using IP address, you will get certificate failure error.

In our self-signed certificates, we added IP entries which allows us to visit the url with IP. But this is not quite common in external certificate.

**Comment by NakulManchanda** [comment]
Thanks @jackjia-ibm  for example, missed your comments, we end up not merging this, found alternate with another PR
https://github.com/zowe/explorer-jes/pull/183
by using both in ip and host in csp header.

Separate root cause to identify if IP address is public or not will be handled in install packaging repo.

**Pull request closed without merging**
