### PR TITLE
encoding the prefix before sending it in URL

### PR DESCRIPTION
**Pull request by AdarshdeepCheema**
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>

This PR addresses Issue: https://github.com/zowe/zlux/issues/820

## PR Type
- [ ] Bug fix
- [ ] Feature
- [ ] Other (Please indicate)

## PR Checklist
- [ ] PR completes `npm run preCommit` without error
- [ ] Relevant Test cases have been added (Unit and or FVT)
- [ ] Relevant update to CHANGELOG.md
- [ ] PR from forked repo? Ensure Allow edits by maintaners is set.

### CODE REVIEW

**Review by skurnevich — CHANGES_REQUESTED** [review]
Fix looks good, jobs with names containing '#' sign are displayed fine now. But note that some other special chars are still displayed as '?'.
Could you please fix linter warnings? For the "Unexpected confirm" warning we can update the .eslintrc.js rules with "no-alert": 0

**Comment by AdarshdeepCheema** [comment]
> Fix looks good, jobs with names containing '#' sign are displayed fine now. But note that some other special chars are still displayed as '?'. Could you please fix linter warnings? For the "Unexpected confirm" warning we can update the .eslintrc.js rules with "no-alert": 0

Lint warnings are fixed,
This PR is only for prefixes with '#'. 
The special character gets converted into '?' issue seems like the design or issue on JES side. And we cannot access such JOBs in JES is zOSMF issue. These two will be handled separately.

**Review by skurnevich — APPROVED** [review]

**Comment by Martin-Zeithaml** [comment]
The **Download JCL** does not work for some jobs, there is missing ```encodeURLComponent``` in the ```JobInstance.js/handleDownloadJCL()```.
Otherwise looks good:

image

**Comment by AdarshdeepCheema** [comment]
> The **Download JCL** does not work for some jobs, there is missing `encodeURLComponent` in the `JobInstance.js/handleDownloadJCL()`. Otherwise looks good:
> 
> image

FIXED.. thx

**Review by Martin-Zeithaml — APPROVED** [review]
**Actions for job - all ok**
- Open
- Cancel Job
- Purge (one or multiple)
- GetJCL
- Download JCL
- Download All Files

**Actions for job file - all ok**
- Download
- Open in Fullscreen

No problems with jobnames containing '#', '$' and '@'.

**Pull request merged**
