### PR TITLE
show the number of jobs found and add the filter option to sort the jobs using prefix and job ID

### PR DESCRIPTION
**Pull request by AdarshdeepCheema**
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>

This PR addresses Issue: https://github.com/zowe/zlux/issues/565

## PR Type
- [ ] Bug fix
- [x] Feature
- [ ] Other (Please indicate)

## PR Checklist
- [x] PR completes `npm run preCommit` without error
- [ ] Relevant Test cases have been added (Unit and or FVT)
- [x] Relevant update to CHANGELOG.md
- [ ] PR from forked repo? Ensure Allow edits by maintaners is set.

### CODE REVIEW

**Comment by AdarshdeepCheema** [comment]
Screen Shot 2022-08-22 at 3 10 36 PM

**Comment by AdarshdeepCheema** [comment]
Screen Shot 2022-08-22 at 3 13 01 PM

**Comment by AdarshdeepCheema** [comment]
Screen Shot 2022-08-23 at 11 43 06 AM

**Comment by AdarshdeepCheema** [comment]
Screen Shot 2022-09-05 at 1 06 38 PM

**Review by 1000TurquoisePogs — APPROVED** [review]

**Pull request merged**
