### PR TITLE
Keyring packaging fix

### PR DESCRIPTION
**Pull request by NakulManchanda**
This PR addresses Issue:
https://github.com/zowe/explorer-ui-server/issues/35

Properly packaging keyring_js to avoid node-gyp issue, by including pre-build version

## PR Type
- [X ] Bug fix
- [ ] Feature
- [ ] Other (Please indicate)

## PR Checklist
- [ ] PR completes `npm run preCommit` without error
- [ ] Relevant Test cases have been added (Unit and or FVT)
- [ ] Relevant update to CHANGELOG.md
- [ ] PR from forked repo? Ensure Allow edits by maintaners is set.

### CODE REVIEW

**Comment by NakulManchanda** [comment]
@js665999 do you have any suggestions?

**Comment by NakulManchanda** [comment]
added keyring_js and node-gyp to package-lock.json manually, as couldn't get that refreshed my local-windows environement

**Comment by vit-tomica** [comment]
@NakulManchanda  Hi Nakul, this is not a correct approach. We should not try to build the native binaries here. Binaries have been built and shipped as part of the keyring_js npm package.

**Comment by vit-tomica** [comment]
Could we try to add the `npm install keyring_js --ignore-scripts` command behind the line here:
https://github.com/zowe/explorer-jes/blob/de87830f3493b17e7c36377316feb5281c3783e1/.pax/prepare-workspace.sh#L47

It should suppress building the native binaries which is failing on any platform other than s390. The keyring_js and node-gyp-build should be installed to the node_modules directory with the `--ignore-scripts' option

**Pull request merged**
